# Specify the version number
version: "1"
services:
  main_app:
    image: main_app
    ports:
      - "8000:8000"
    container_name: "main_app"
    restart: always
    networks:
      - webforum

  users_app:
    image: users_app
    ports:
      - "8001:8001"
    container_name: "users_app"
    restart: always
    networks:
      - webforum
    
  posts_app:
    image: posts_app
    ports:
      - "8002:8002"
    container_name: "posts_app"
    restart: always
    networks:
      - webforum

  comments_app:
    image: comments_app
    ports:
      - "8003:8003"
    container_name: "comments_app"
    restart: always
    networks:
      - webforum

networks:
  webforum:
    driver: bridge