# Specify the version number
version: "3"
services:
  main_app:
    #build:
    #  context: ./main_app
    image: zgalicfoi/main_app:base
    ports:
      - "80:80"
    container_name: "main_app"
    restart: always
    networks:
      - webforum

  users_app:
    #build:
    #  context: ./users_app
    image: zgalicfoi/users_app:base
    ports:
      - "81:81"
    container_name: "users_app"
    restart: always
    networks:
      - webforum
    
  posts_app:
    #build:
    #  context: ./posts_app
    image: zgalicfoi/posts_app:base
    ports:
      - "82:82"
    container_name: "posts_app"
    restart: always
    networks:
      - webforum

  comments_app:
    #build:
    #  context: ./comments_app
    image: zgalicfoi/comments_app:base
    ports:
      - "83:83"
    container_name: "comments_app"
    restart: always
    networks:
      - webforum

networks:
  webforum:
